language: ruby
rvm:
 - 2.5.0
cache:
  - bundler: true

before_install: gem install bundler
notifications:
  -false

before_script:
  - bundle exec rails db:create 
  - bundle exec rails db:migrate

script:
  - bundle exec rspec spec        # rspec testing
