language: ruby
rvm:
 - 2.5.0
cache:
  - bundler: true

before_install: gem install bundler
notifications:
  -false

before_script:
  - bundle exec rails db:create 
  - bundle exec rails db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec spec        # rspec testing
  - "sbt clean coverage test"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bundle exec rake coveralls:push

after_success:
- "sbt coveralls"
